build:
  command: npm run export; npm run subfont;
  publish: __sapper__/export

plugins:
  - type: netlify-plugin-subfont
    config:
      entryPoints:
        - "*.html"
      recursive: true
      fontDisplay: swap
      inlineCss: false
      inlineFonts: false
